name: Android CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build APK with Gradle
      run: ./gradlew assemble
    - name: Copy ,commit and push release APK to root DIR
      run:  git config --global user.name "bansalayush" && cp app/build/outputs/apk/release/app-release-unsigned.apk ./ && git add app-release-unsigned.apk && git commit -m "upload release apk" && git push origin master
  
#   publish: 
#     needs: build
#     runs-on: ubuntu-latest
    
      
      
      
      
      
      
      
      
      
      
      
      
      
